sudo: false
language: node_js
# test historically supported versions, lts, and current stable version
node_js:
  - "6"
  - "8"
  - "lts/*"
  - "node"
install: yarn install
script: "npm run-script ci"
